const express = require('express')
const router = express.Router()
const listController = require('../controllers/list.controller')
const { authRequired } = require('../middlewares/validateToken')
const { validateSchema } = require('../middlewares/validator.middleware')
const { createListSchema, updateListSchema } = require('../schemas/list.schema')

router.post('/', authRequired, validateSchema(createListSchema), listController.createList)
router.get('/:listId', authRequired, listController.getListById)
router.get('/', authRequired, listController.getLists)
router.put('/:listId', authRequired, validateSchema(updateListSchema), listController.updateList)
router.delete('/:listId', authRequired, listController.deleteList)